name: Deploy branch
on:
  push:
    branches:
      - '*'

permissions:
  contents: 'write'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: Build
        run: npm run build # o el comando que utilices para generar el build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build # o el directorio donde se encuentra el build
