name: Deploy on Comment

on:
  pull_request_review_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy code
        run: |
          if [ "${{ github.event.comment.body }}" == "deploy" ]; then
            git checkout ${{ github.event.pull_request.head.ref }}
            git push origin HEAD
          fi
      - name: Create deployment comment
          uses: peter-evans/create-or-update-comment@v1
          with:
            body: 'Se ha realizado el despliegue con éxito!'
            issue-number: ${{ github.event.number }}