name: Deploy on Comment

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy code
        run: |
          if [ "${{ github.event.comment.body }}" == "deploy" ]; then
            git checkout ${{ github.event.pull_request.head.ref }}
            git push origin HEAD
          fi