name: CI

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create commit comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MESSAGE="
          Changed features
          Update eslint from ~7.18.0 to ^8.13.0
          Update eslint-config-standard from 16.0.3 to 17.0.0 to adapt to ESLint 8
          Update eslint-config-standard-jsx from 10.0.0 to ^11.0.0 to adapt to ESLint 8
          Update standard-engine from ^14 to ^15.0.0 to adapt to ESLint 8, see its CHANGELOG
          Move from eslint-plugin-node@~11.1.0 to eslint-plugin-n@^15.1.0 to adapt to ESLint 8
          Update eslint-plugin-import
          Update eslint-plugin-promise
          Update eslint-plugin-react
          "
          
          gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"