name: comments

on:
  issue_comment:
    types: [ created ]
    branches:
      - main
      - 'releases/**'

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create comment on pr
        if: ${{ github.event.issue.pull_request }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MESSAGE="
          linea primera
          linea segunda
          Create comment on pr
          "
          gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"

      - name: Create comment on issue
          if: ${{ !github.event.issue.pull_request }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            MESSAGE="
            linea primera
            linea segunda
            Create comment on issue
            "
            gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"