name: commentstrigger

on:
  issue_comment:
    types: [ created ]

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create comment on pr
        if: [ "${{ github.event.issue.pull_request }}" != "null" ]; then
          MESSAGE="
          linea primera
          linea segunda
          Create comment on pr
          "
        else
          MESSAGE="
          linea primera
          linea segunda
          Create comment on issue
          "
        fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"
