name: commentstrigger

on:
  issue_comment:
    types: [ created ]
  
permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create comment on pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          if [[ "${{ github.event.comment.body }}" == "deploy" ]]; then
             MESSAGE="lee el comentario"
             gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"
          else
            MESSAGE="no lee una mierda"
            gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"
          fi
