name: Comment during a deploy

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create deployment comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: 'Se ha realizado el despliegue con éxito!'
          issue-number: ${{ github.event.number }}