name: CI

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check changelog
        run: |
          git show $(git log --all -i --grep='2.20.0' --pretty=format:"%H" -1 code/changelog.md)

      - name: Create commit comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.number }} --body "$(echo -e "Hello, world!")"
            

